---
abstract: 'Puts the MANIFEST file in the project root'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Dist::Zilla: '4.300033'
  Module::Build: '0.4004'
  Test::Requires: '0.06'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-ManifestInRoot
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Dist::Zilla::Plugin::ManifestInRoot:
    file: lib/Dist/Zilla/Plugin/ManifestInRoot.pm
    version: v0.6.1
requires:
  Dist::Zilla: '4.300033'
  Moose: '2.0802'
  Moose::Autobox: '0.12'
  namespace::autoclean: '0.13'
  perl: '5.008'
  version: '0.88'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-ManifestInRoot
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.6.1
